// Code generated by dagger-compiler.  Do not edit.
package com.donnfelker.android.bootstrap.util;


import dagger.internal.Binding;
import dagger.internal.Linker;
import dagger.internal.StaticInjection;

/**
 * A manager for {@code Ln}'s injections into static fields.
 */
public final class Ln$$StaticInjection extends StaticInjection {
  private Binding<com.donnfelker.android.bootstrap.util.Ln.BaseConfig> config;
  private Binding<com.donnfelker.android.bootstrap.util.Ln.Print> print;

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  public void attach(Linker linker) {
    config = (Binding<com.donnfelker.android.bootstrap.util.Ln.BaseConfig>) linker.requestBinding("com.donnfelker.android.bootstrap.util.Ln$BaseConfig", com.donnfelker.android.bootstrap.util.Ln.class);
    print = (Binding<com.donnfelker.android.bootstrap.util.Ln.Print>) linker.requestBinding("com.donnfelker.android.bootstrap.util.Ln$Print", com.donnfelker.android.bootstrap.util.Ln.class);
  }

  /**
   * Performs the injections of dependencies into static fields when requested by
   * the {@code dagger.ObjectGraph}.
   */
  @Override
  public void inject() {
    Ln.config = config.get();
    Ln.print = print.get();
  }
}
